#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys

from validate_catalog_contract import is_valid_rust_identifier


ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = ROOT / "catalog" / "units-catalog.json"
SUMMARY_PATH = ROOT / "catalog" / "generated" / "units-catalog-summary.json"
RUST_PATH = ROOT / "crates" / "units-x" / "src" / "generated" / "catalog_metadata.rs"
FFI_TYPES_PATH = ROOT / "crates" / "units-x" / "src" / "generated" / "ffi_contract_types.rs"
PUBLIC_TYPES_PATH = ROOT / "crates" / "units-x" / "src" / "generated" / "public_types.rs"


def load_catalog() -> dict:
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def build_summary(catalog: dict) -> dict:
    dimensions = catalog["dimensions"]
    return {
        "catalog_version": catalog["catalog_version"],
        "dimension_count": len(dimensions),
        "dimensions": [
            {
                "dimension_id": dimension["dimension_id"],
                "canonical_dimension_id": dimension["canonical_dimension_id"],
                "family": dimension["family"],
                "public_type": dimension["public_type"],
                "base_unit_code_id": dimension["base_unit_code_id"],
                "scalar": dimension["json_forms"]["scalar"],
                "small_array": dimension["json_forms"]["small_array"],
                "buffer": dimension["json_forms"]["buffer"],
                "abi_name_stem": dimension["abi"]["abi_name_stem"],
                "binary_schema_id": dimension["abi"]["binary_schema_id"],
                "units": [
                    {
                        "unit_code_id": unit["unit_code_id"],
                        "unit_symbol": unit["unit_symbol"],
                        "binary_unit_id": unit["binary_unit_id"],
                        "reserved_word_alias": unit["reserved_word_alias"],
                    }
                    for unit in dimension["units"]
                ],
                "unit_ids": [unit["binary_unit_id"] for unit in dimension["units"]],
            }
            for dimension in dimensions
        ],
    }


def rust_string_literal(value: str) -> str:
    pieces = ['"']
    for char in value:
        if char == "\\":
            pieces.append("\\\\")
        elif char == '"':
            pieces.append('\\"')
        elif char == "\n":
            pieces.append("\\n")
        elif char == "\r":
            pieces.append("\\r")
        elif char == "\t":
            pieces.append("\\t")
        else:
            codepoint = ord(char)
            if codepoint < 0x20 or codepoint == 0x7F:
                pieces.append(f"\\x{codepoint:02x}")
            elif codepoint > 0x7E:
                pieces.append(f"\\u{{{codepoint:x}}}")
            else:
                pieces.append(char)
    pieces.append('"')
    return "".join(pieces)


def render_rust_module(summary: dict) -> str:
    dimensions = summary["dimensions"]
    lines = [
        "// @generated by scripts/generate_catalog_artifacts.py",
        "",
        "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
        "pub struct CatalogDimensionId(pub &'static str);",
        "",
        "impl CatalogDimensionId {",
        "    pub const fn as_str(self) -> &'static str {",
        "        self.0",
        "    }",
        "}",
        "",
        "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
        "pub struct CatalogTypeId(pub &'static str);",
        "",
        "impl CatalogTypeId {",
        "    pub const fn as_str(self) -> &'static str {",
        "        self.0",
        "    }",
        "}",
        "",
        "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
        "pub struct CatalogTypeIdTemplate(pub &'static str);",
        "",
        "impl CatalogTypeIdTemplate {",
        "    pub const fn as_str(self) -> &'static str {",
        "        self.0",
        "    }",
        "}",
        "",
        "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
        "pub struct CatalogBinarySchemaId(pub &'static str);",
        "",
        "impl CatalogBinarySchemaId {",
        "    pub const fn as_str(self) -> &'static str {",
        "        self.0",
        "    }",
        "}",
        "",
        "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
        "pub enum CatalogJsonEncoding {",
        "    Object,",
        "    Array,",
        "    Base64Le,",
        "}",
        "",
        "impl CatalogJsonEncoding {",
        "    pub const fn as_str(self) -> &'static str {",
        "        match self {",
        '            Self::Object => "object",',
        '            Self::Array => "array",',
        '            Self::Base64Le => "base64-le",',
        "        }",
        "    }",
        "}",
        "",
        "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
        "pub struct CatalogDimensionMetadata {",
        "    pub dimension_id: CatalogDimensionId,",
        "    pub canonical_dimension_id: CatalogDimensionId,",
        "    pub public_type: &'static str,",
        "    pub scalar_type_ids: &'static [CatalogTypeId],",
        "    pub scalar_encoding: CatalogJsonEncoding,",
        "    pub small_array_type_id_template: CatalogTypeIdTemplate,",
        "    pub small_array_encoding: CatalogJsonEncoding,",
        "    pub buffer_type_id_template: CatalogTypeIdTemplate,",
        "    pub buffer_encoding: CatalogJsonEncoding,",
        "    pub binary_schema_id: CatalogBinarySchemaId,",
        "}",
        "",
        f"pub const CATALOG_VERSION: &str = {rust_string_literal(summary['catalog_version'])};",
        f"pub const DIMENSION_COUNT: usize = {summary['dimension_count']};",
        "pub const DIMENSIONS: &[CatalogDimensionMetadata] = &[",
    ]
    for dimension in dimensions:
        scalar_literals = ", ".join(
            f"CatalogTypeId({rust_string_literal(value)})" for value in dimension["scalar"]["type_ids"]
        )
        scalar_encoding = rust_encoding_variant(dimension["scalar"]["encoding"])
        small_array_encoding = rust_encoding_variant(dimension["small_array"]["encoding"])
        buffer_encoding = rust_encoding_variant(dimension["buffer"]["encoding"])
        lines.extend(
            [
                "    CatalogDimensionMetadata {",
                f"        dimension_id: CatalogDimensionId({rust_string_literal(dimension['dimension_id'])}),",
                f"        canonical_dimension_id: CatalogDimensionId({rust_string_literal(dimension['canonical_dimension_id'])}),",
                f"        public_type: {rust_string_literal(dimension['public_type'])},",
                f"        scalar_type_ids: &[{scalar_literals}],",
                f"        scalar_encoding: CatalogJsonEncoding::{scalar_encoding},",
                f"        small_array_type_id_template: CatalogTypeIdTemplate({rust_string_literal(dimension['small_array']['type_id_template'])}),",
                f"        small_array_encoding: CatalogJsonEncoding::{small_array_encoding},",
                f"        buffer_type_id_template: CatalogTypeIdTemplate({rust_string_literal(dimension['buffer']['type_id_template'])}),",
                f"        buffer_encoding: CatalogJsonEncoding::{buffer_encoding},",
                f"        binary_schema_id: CatalogBinarySchemaId({rust_string_literal(dimension['binary_schema_id'])}),",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines) + "\n"


def rust_encoding_variant(value: str) -> str:
    if value == "object":
        return "Object"
    if value == "array":
        return "Array"
    if value == "base64-le":
        return "Base64Le"
    raise ValueError(f"unsupported encoding: {value}")


def rust_identifier(value: str) -> str:
    pieces: list[str] = []
    for char in value:
        if char.isascii() and (char.isalnum() or char == "_"):
            pieces.append(char)
        else:
            pieces.append("_")
    rendered = "".join(pieces)
    if not rendered:
        return "_"
    if rendered[0].isdigit():
        return f"_{rendered}"
    return rendered


def render_generated_ffi_types(summary: dict) -> str:
    dimensions = summary["dimensions"]
    exemplar_dimension = next(dimension for dimension in dimensions if dimension["dimension_id"] == "distance")
    exemplar_unit = next(unit for unit in exemplar_dimension["units"] if unit["unit_code_id"] == "mm")
    scalar_type_id = next(value for value in exemplar_dimension["scalar"]["type_ids"] if value.endswith("_i32"))
    storage = scalar_type_id.rsplit("_", maxsplit=1)[1]
    abi_name_stem = exemplar_dimension["abi_name_stem"]
    unit_code_id = exemplar_unit["unit_code_id"]
    type_name = rust_identifier(f"{abi_name_stem}_{unit_code_id}_{storage}")
    field_name = rust_identifier(f"value_{unit_code_id}")
    slice_name = rust_identifier(f"{type_name}_slice")
    slice_mut_name = rust_identifier(f"{type_name}_slice_mut")

    lines = [
        "// @generated by scripts/generate_catalog_artifacts.py",
        "#![allow(non_camel_case_types)]",
        "",
    ]
    lines.extend(
        [
            "/// ABI-facing scalar name pattern generated from catalog naming metadata.",
            "#[repr(C)]",
            "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
            f"pub struct {type_name} {{",
            f"    pub {field_name}: i32,",
            "}",
            "",
            "/// ABI slice pattern generated from catalog naming metadata.",
            "#[repr(C)]",
            "#[derive(Copy, Clone, Debug)]",
            f"pub struct {slice_name} {{",
            f"    pub ptr: *const {type_name},",
            "    pub len: u64,",
            "}",
            "",
            f"impl {slice_name} {{",
            "    pub const fn is_contract_valid(self) -> bool {",
            "        self.ptr.is_null() == (self.len == 0)",
            "    }",
            "}",
            "",
            "/// Mutable ABI slice pattern generated from catalog naming metadata.",
            "#[repr(C)]",
            "#[derive(Copy, Clone, Debug)]",
            f"pub struct {slice_mut_name} {{",
            f"    pub ptr: *mut {type_name},",
            "    pub len: u64,",
            "}",
            "",
            f"impl {slice_mut_name} {{",
            "    pub const fn is_contract_valid(self) -> bool {",
            "        self.ptr.is_null() == (self.len == 0)",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def render_generated_public_types(summary: dict) -> str:
    dimensions = summary["dimensions"]
    unit_rows: list[dict[str, str]] = []
    seen_markers: set[str] = set()
    lines = [
        "// @generated by scripts/generate_catalog_artifacts.py",
        "#![allow(non_camel_case_types, non_snake_case)]",
        "",
        "use crate::model::{private, Quantity, QuantityType, UnitMarker};",
        "",
        "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
        "pub struct GeneratedUnitMetadata {",
        "    pub unit_code_id: &'static str,",
        "    pub unit_symbol: &'static str,",
        "    pub dimension_id: &'static str,",
        "    pub canonical_dimension_id: &'static str,",
        "    pub public_type: &'static str,",
        "}",
        "",
        "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
        "pub struct GeneratedPublicTypeMetadata {",
        "    pub public_type: &'static str,",
        "    pub dimension_id: &'static str,",
        "    pub canonical_dimension_id: &'static str,",
        "    pub default_unit_code_id: &'static str,",
        "    pub scalar_type_ids: &'static [&'static str],",
        "    pub supported_units: &'static [&'static str],",
        "}",
        "",
    ]

    def marker_name_for_unit(unit: dict[str, object]) -> str:
        marker_source = unit["reserved_word_alias"] or unit["unit_code_id"]
        if not is_valid_rust_identifier(marker_source):
            raise ValueError(f"invalid generated Rust marker: {marker_source}")
        return rust_identifier(marker_source)

    def default_marker_for_dimension(dimension: dict[str, object]) -> str:
        base_unit_code_id = dimension["base_unit_code_id"]
        for unit in dimension["units"]:
            if unit["unit_code_id"] == base_unit_code_id:
                return marker_name_for_unit(unit)
        raise ValueError(
            f"missing base unit `{base_unit_code_id}` for dimension `{dimension['dimension_id']}`"
        )

    for dimension in dimensions:
        for unit in dimension["units"]:
            marker = marker_name_for_unit(unit)
            if marker in seen_markers:
                raise ValueError(f"duplicate generated Rust marker: {marker}")
            seen_markers.add(marker)
            unit_rows.append(
                {
                    "marker": marker,
                    "unit_code_id": unit["unit_code_id"],
                    "unit_symbol": unit["unit_symbol"],
                    "dimension_id": dimension["dimension_id"],
                    "canonical_dimension_id": dimension["canonical_dimension_id"],
                    "public_type": dimension["public_type"],
                }
            )
            lines.extend(
                [
                    f"/// Unit marker generated from catalog unit `{unit['unit_code_id']}`.",
                    "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
                    f"pub struct {marker};",
                    "",
                    f"impl private::SealedUnit for {marker} {{}}",
                    "",
                    f"impl UnitMarker for {marker} {{",
                    f"    const UNIT_SYMBOL: &'static str = {rust_string_literal(unit['unit_symbol'])};",
                    f"    const UNIT_CODE_ID: &'static str = {rust_string_literal(unit['unit_code_id'])};",
                    f"    const DIMENSION_ID: &'static str = {rust_string_literal(dimension['dimension_id'])};",
                    f"    const CANONICAL_DIMENSION_ID: &'static str = {rust_string_literal(dimension['canonical_dimension_id'])};",
                    f"    const PUBLIC_TYPE: &'static str = {rust_string_literal(dimension['public_type'])};",
                    "}",
                    "",
                ]
            )

    lines.extend(
        [
            f"pub const GENERATED_UNIT_COUNT: usize = {len(unit_rows)};",
            "pub const UNIT_METADATA: &[GeneratedUnitMetadata] = &[",
        ]
    )
    for row in unit_rows:
        lines.extend(
            [
                "    GeneratedUnitMetadata {",
                f"        unit_code_id: {rust_string_literal(row['unit_code_id'])},",
                f"        unit_symbol: {rust_string_literal(row['unit_symbol'])},",
                f"        dimension_id: {rust_string_literal(row['dimension_id'])},",
                f"        canonical_dimension_id: {rust_string_literal(row['canonical_dimension_id'])},",
                f"        public_type: {rust_string_literal(row['public_type'])},",
                "    },",
            ]
        )
    lines.extend(["];", ""])

    for dimension in dimensions:
        public_type = dimension["public_type"]
        default_unit = default_marker_for_dimension(dimension)
        unit_trait = f"{public_type}Unit"
        lines.extend(
            [
                f"/// Sealed unit-family marker trait for `{public_type}`.",
                "///",
                "/// External crates cannot implement this trait; only",
                "/// catalog-generated unit markers participate in this family.",
                f"pub trait {unit_trait}: UnitMarker {{}}",
                "",
            ]
        )
        for unit in dimension["units"]:
            marker = marker_name_for_unit(unit)
            lines.extend(
                [
                    f"impl {unit_trait} for {marker} {{}}",
                    "",
                ]
            )
        lines.extend(
            [
                "#[repr(transparent)]",
                "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
                f"pub struct {public_type}<Storage = f64, Unit = {default_unit}>",
                "where",
                f"    Unit: {unit_trait},",
                "{",
                "    quantity: Quantity<Unit, Storage>,",
                "}",
                "",
                f"impl<Storage, Unit> private::SealedQuantityType for {public_type}<Storage, Unit>",
                "where",
                f"    Unit: {unit_trait},",
                "{}",
                "",
                f"impl<Storage, Unit> {public_type}<Storage, Unit>",
                "where",
                f"    Unit: {unit_trait},",
                "{",
                f"    pub const PUBLIC_TYPE: &'static str = {rust_string_literal(dimension['public_type'])};",
                f"    pub const DIMENSION_ID: &'static str = {rust_string_literal(dimension['dimension_id'])};",
                f"    pub const CANONICAL_DIMENSION_ID: &'static str = {rust_string_literal(dimension['canonical_dimension_id'])};",
                "",
                "    pub const fn new(storage: Storage) -> Self {",
                "        Self {",
                "            quantity: Quantity::new(storage),",
                "        }",
                "    }",
                "",
                "    pub const fn value_ref(&self) -> &Storage {",
                "        &self.quantity.storage",
                "    }",
                "",
                "    pub fn value(&self) -> Storage",
                "    where",
                "        Storage: Copy,",
                "    {",
                "        self.quantity.storage",
                "    }",
                "",
                "    pub fn value_mut(&mut self) -> &mut Storage {",
                "        &mut self.quantity.storage",
                "    }",
                "",
                "    pub fn into_value(self) -> Storage {",
                "        self.quantity.storage",
                "    }",
                "",
                "    pub const fn unit(&self) -> &'static str {",
                "        Unit::UNIT_SYMBOL",
                "    }",
                "",
                "    pub const fn unit_code_id(&self) -> &'static str {",
                "        Unit::UNIT_CODE_ID",
                "    }",
                "",
                "    pub const fn dimension_id(&self) -> &'static str {",
                "        Self::DIMENSION_ID",
                "    }",
                "",
                "    pub const fn canonical_dimension_id(&self) -> &'static str {",
                "        Self::CANONICAL_DIMENSION_ID",
                "    }",
                "",
                "    pub const fn as_quantity(&self) -> &Quantity<Unit, Storage> {",
                "        &self.quantity",
                "    }",
                "",
                "    pub fn as_quantity_mut(&mut self) -> &mut Quantity<Unit, Storage> {",
                "        &mut self.quantity",
                "    }",
                "",
                "    pub fn into_quantity(self) -> Quantity<Unit, Storage> {",
                "        self.quantity",
                "    }",
                "",
                "    pub fn from_quantity(quantity: Quantity<Unit, Storage>) -> Self {",
                "        Self { quantity }",
                "    }",
                "}",
                "",
                f"impl<Storage, Unit> QuantityType for {public_type}<Storage, Unit>",
                "where",
                f"    Unit: {unit_trait},",
                "{",
                "    type Storage = Storage;",
                "    type Unit = Unit;",
                "",
                f"    const PUBLIC_TYPE: &'static str = {rust_string_literal(dimension['public_type'])};",
                f"    const DIMENSION_ID: &'static str = {rust_string_literal(dimension['dimension_id'])};",
                f"    const CANONICAL_DIMENSION_ID: &'static str = {rust_string_literal(dimension['canonical_dimension_id'])};",
                "",
                "    fn from_quantity(quantity: Quantity<Unit, Storage>) -> Self {",
                "        Self { quantity }",
                "    }",
                "",
                "    fn quantity(&self) -> &Quantity<Unit, Storage> {",
                "        &self.quantity",
                "    }",
                "",
                "    fn quantity_mut(&mut self) -> &mut Quantity<Unit, Storage> {",
                "        &mut self.quantity",
                "    }",
                "",
                "    fn into_quantity(self) -> Quantity<Unit, Storage> {",
                "        self.quantity",
                "    }",
                "}",
                "",
            ]
        )
        for unit in dimension["units"]:
            marker = rust_identifier(unit["reserved_word_alias"] or unit["unit_code_id"])
            ctor = marker
            lines.extend(
                [
                    f"impl<Storage> {public_type}<Storage, {marker}> {{",
                    f"    pub const fn {ctor}(storage: Storage) -> Self {{",
                    "        Self::new(storage)",
                    "    }",
                    "}",
                    "",
                ]
            )

    lines.extend(
        [
            f"pub const GENERATED_PUBLIC_TYPE_COUNT: usize = {len(dimensions)};",
            "pub const PUBLIC_TYPE_METADATA: &[GeneratedPublicTypeMetadata] = &[",
        ]
    )
    for dimension in dimensions:
        scalar_type_literals = ", ".join(
            rust_string_literal(type_id) for type_id in dimension["scalar"]["type_ids"]
        )
        supported_unit_literals = ", ".join(
            rust_string_literal(unit["unit_code_id"]) for unit in dimension["units"]
        )
        lines.extend(
            [
                "    GeneratedPublicTypeMetadata {",
                f"        public_type: {rust_string_literal(dimension['public_type'])},",
                f"        dimension_id: {rust_string_literal(dimension['dimension_id'])},",
                f"        canonical_dimension_id: {rust_string_literal(dimension['canonical_dimension_id'])},",
                f"        default_unit_code_id: {rust_string_literal(dimension['base_unit_code_id'])},",
                f"        scalar_type_ids: &[{scalar_type_literals}],",
                f"        supported_units: &[{supported_unit_literals}],",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines) + "\n"


def format_rust_source(source: str) -> str:
    completed = subprocess.run(
        ["rustfmt", "--emit", "stdout"],
        input=source,
        text=True,
        encoding="utf-8",
        errors="strict",
        capture_output=True,
        check=True,
    )
    return completed.stdout


def expected_outputs() -> dict[Path, str]:
    catalog = load_catalog()
    summary = build_summary(catalog)
    return {
        SUMMARY_PATH: json.dumps(summary, indent=2, sort_keys=True) + "\n",
        RUST_PATH: format_rust_source(render_rust_module(summary)),
        FFI_TYPES_PATH: format_rust_source(render_generated_ffi_types(summary)),
        PUBLIC_TYPES_PATH: format_rust_source(render_generated_public_types(summary)),
    }


def write_outputs() -> None:
    for path, content in expected_outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def check_outputs() -> int:
    mismatches: list[str] = []
    for path, expected in expected_outputs().items():
        if not path.exists():
            mismatches.append(f"missing generated file: {path.relative_to(ROOT).as_posix()}")
            continue
        actual = path.read_bytes()
        if actual != expected.encode("utf-8"):
            mismatches.append(f"generated file drift: {path.relative_to(ROOT).as_posix()}")
    if mismatches:
        for mismatch in mismatches:
            print(mismatch, file=sys.stderr)
        return 1
    print("catalog generation check passed")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate or verify catalog bootstrap artifacts.")
    parser.add_argument("--mode", choices=("write", "check"), default="write")
    args = parser.parse_args(argv[1:])
    if args.mode == "write":
        write_outputs()
        return 0
    return check_outputs()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
