#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = ROOT / "catalog" / "units-catalog.json"
SUMMARY_PATH = ROOT / "catalog" / "generated" / "units-catalog-summary.json"
RUST_PATH = ROOT / "crates" / "units-x" / "src" / "generated" / "catalog_metadata.rs"


def load_catalog() -> dict:
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def build_summary(catalog: dict) -> dict:
    dimensions = catalog["dimensions"]
    return {
        "catalog_version": catalog["catalog_version"],
        "dimension_count": len(dimensions),
        "dimensions": [
            {
                "dimension_id": dimension["dimension_id"],
                "public_type": dimension["public_type"],
                "scalar_type_ids": dimension["json_forms"]["scalar_type_ids"],
                "small_array_type_id_template": dimension["json_forms"]["small_array_type_id_template"],
                "default_encoding": dimension["json_forms"]["default_encoding"],
                "buffer_type_id_template": dimension["json_forms"]["buffer_type_id_template"],
                "binary_schema_id": dimension["abi"]["binary_schema_id"],
                "units": [
                    {
                        "unit_code_id": unit["unit_code_id"],
                        "binary_unit_id": unit["binary_unit_id"],
                        "reserved_word_alias": unit["reserved_word_alias"],
                    }
                    for unit in dimension["units"]
                ],
                "unit_ids": [unit["binary_unit_id"] for unit in dimension["units"]],
            }
            for dimension in dimensions
        ],
    }


def rust_string_literal(value: str) -> str:
    return json.dumps(value)


def render_rust_module(summary: dict) -> str:
    dimensions = summary["dimensions"]
    lines = [
        "// @generated by scripts/generate_catalog_artifacts.py",
        "",
        "#[derive(Copy, Clone, Debug, PartialEq, Eq)]",
        "pub struct CatalogDimensionMetadata {",
        "    pub dimension_id: &'static str,",
        "    pub public_type: &'static str,",
        "    pub scalar_type_ids: &'static [&'static str],",
        "    pub small_array_type_id_template: &'static str,",
        "    pub default_encoding: &'static str,",
        "    pub buffer_type_id_template: &'static str,",
        "    pub binary_schema_id: &'static str,",
        "}",
        "",
        f"pub const CATALOG_VERSION: &str = {rust_string_literal(summary['catalog_version'])};",
        f"pub const DIMENSION_COUNT: usize = {summary['dimension_count']};",
        "pub const DIMENSIONS: &[CatalogDimensionMetadata] = &[",
    ]
    for dimension in dimensions:
        scalar_literals = ", ".join(rust_string_literal(value) for value in dimension["scalar_type_ids"])
        lines.extend(
            [
                "    CatalogDimensionMetadata {",
                f"        dimension_id: {rust_string_literal(dimension['dimension_id'])},",
                f"        public_type: {rust_string_literal(dimension['public_type'])},",
                f"        scalar_type_ids: &[{scalar_literals}],",
                f"        small_array_type_id_template: {rust_string_literal(dimension['small_array_type_id_template'])},",
                f"        default_encoding: {rust_string_literal(dimension['default_encoding'])},",
                f"        buffer_type_id_template: {rust_string_literal(dimension['buffer_type_id_template'])},",
                f"        binary_schema_id: {rust_string_literal(dimension['binary_schema_id'])},",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def expected_outputs() -> dict[Path, str]:
    catalog = load_catalog()
    summary = build_summary(catalog)
    return {
        SUMMARY_PATH: json.dumps(summary, indent=2, sort_keys=True) + "\n",
        RUST_PATH: render_rust_module(summary),
    }


def write_outputs() -> None:
    for path, content in expected_outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_outputs() -> int:
    mismatches: list[str] = []
    for path, expected in expected_outputs().items():
        if not path.exists():
            mismatches.append(f"missing generated file: {path.relative_to(ROOT).as_posix()}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            mismatches.append(f"generated file drift: {path.relative_to(ROOT).as_posix()}")
    if mismatches:
        for mismatch in mismatches:
            print(mismatch, file=sys.stderr)
        return 1
    print("catalog generation check passed")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate or verify catalog bootstrap artifacts.")
    parser.add_argument("--mode", choices=("write", "check"), default="write")
    args = parser.parse_args(argv[1:])
    if args.mode == "write":
        write_outputs()
        return 0
    return check_outputs()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
